title: QiiDB
description:
keywords:
tagline: 基于文件存储的开放数据集合

collections:
  pages:
    output: true
    permalink: /:path/
  cookbook:
    output: true
    permalink: /:path/
  api:
    output: true
    permalink: /:path/

# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - .vscode
  - node_modules
  - build
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - package-lock.json
  - CNAME
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      css:
        - pages/post
      js:
        - initializers/time
        - initializers/lazyload
      author:
        name: 欧雷
        email: ourairyu@gmail.com
        uri: https://ourai.ws/
        slug: ourai
        twitter: ourairyu
      siblings: true
  - scope:
      path: ""
      type: cookbook
    values:
      layout: guide
      css:
        - pages/post
        - pages/doc
      js:
        - initializers/time
        - initializers/lazyload
      repo: cookbook
  - scope:
      path: ""
      type: api
    values:
      layout: guide
      css:
        - pages/post
        - pages/doc
      js:
        - initializers/time
        - initializers/lazyload
      repo: api



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive/category
    tag: archive/tag
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"

# Jekyll Feed
feed:
  path: atom.xml
name: QiiDB
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: https://ourai.ws/
  twitter: ourairyu
github:
  url: https://qiidb.github.io



# =====
# Customized configurations
# =====

# Modules
module:
  comment: false
  share: true
