header:
  navs:
    - text: 探索
      children:
        - text: 读物
          url: /explore/publications/
        - text: 戏剧
          url: /explore/dramas/
        - text: 路线
          url: /explore/routes/
    # - text: 关于
    #   url: /about/
footer:
  links:
    - text: 宅主义
      url: https://otaku-ism.com/
