title: QiiDB
description: Free & Open File-based Database
keywords:
tagline: Free & Open File-based Database

port: 10224

collections:
  pages:
    output: true
    permalink: /:path/

# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - .vscode
  - node_modules
  - build
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - package-lock.json
  - CNAME
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: ksio/default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: ksio/page



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive/category
    tag: archive/tag
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"

# Jekyll Feed
feed:
  path: atom.xml
name: QiiDB
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: https://ourai.ws/
  twitter: ntksol
github:
  url: https://qiidb.github.io



# =====
# Customized configurations
# =====

ksio:
  meta:
    url: https://qiidb.github.io
  brand:
    color: "#0871ab"
  header:
    navs:
      - text: GitHub
        url: https://github.com/qiidb
    navbar:
      placement: right
  footer:
    partial: footer.html
    links:
      - text: KnoSys
        url: https://knosysio.github.io/
  social:
    share: true
